# Quarantine AI Version (Generated by Prompt)
from typing import List

from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel

app = FastAPI(title="AI Task API")


class TaskCreate(BaseModel):
    title: str
    done: bool = False


class Task(TaskCreate):
    id: int


tasks_db: List[Task] = []
current_id = 1


@app.get("/tasks", response_model=List[Task])
def get_tasks():
    return tasks_db


@app.post("/tasks", status_code=status.HTTP_201_CREATED, response_model=Task)
def create_task(task: TaskCreate):
    global current_id
    if not task.title.strip():
        raise HTTPException(status_code=400, detail="Title cannot be empty")
    new_task = Task(id=current_id, **task.model_dump())
    tasks_db.append(new_task)
    current_id += 1
    return new_task


@app.get("/tasks/{task_id}", response_model=Task)
def get_task(task_id: int):
    for task in tasks_db:
        if task.id == task_id:
            return task
    raise HTTPException(status_code=404, detail="Task not found")


@app.delete("/tasks/{task_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_task(task_id: int):
    for i, task in enumerate(tasks_db):
        if task.id == task_id:
            del tasks_db[i]
            return
    raise HTTPException(status_code=404, detail="Task not found")
